### PR TITLE
Show intraline diffs on same line number

### PR DESCRIPTION
**Pull request by hadrielk**
This should address issues #11 and #22, though not with an option setting - just by default.
I can try making it a setting if you prefer.

### CODE REVIEW

**Comment by DougTy** [comment]
Hey, sorry for the wait. Thanks so much for these PRs!
I've tested them out & everything looks great. Merged.

**Comment by aaaxx** [comment]
The issue still happens, sometimes depending on which tab is active when you do the comparison, although I can't figure out by what logic. At first it looked like intraline additions, but not deletions, in the active tab get a blank line in the diff view, but it's not that simple.

**Comment by DougTy** [comment]
@aaaxx Can you provide a reproducible example? Everything seemed fine from my testing. Thanks.

**Comment by aaaxx** [comment]
```text
lorem
ipsum
dolor
```
```text
lorem
ipsum_
dolo
```

When the first one is active, deletion gets a blank line, and when the second one is active, addition.

**Comment by hadrielk** [comment]
Hmmm... I'll take a look

**Comment by hadrielk** [comment]
I see the problem - I'll fix it soon

**Comment by hadrielk** [comment]
should be fixed in PR #25

**Pull request merged**
