### PR TITLE
Provide more user settings

### PR DESCRIPTION
**Pull request by hadrielk**

### CODE REVIEW

**Comment by DougTy** [comment]
Good changes. Didn't realize they added functions for directly hiding things. Cheers.

**Comment by mastef** [comment]
@DougTy @hadrielk this breaks the whole plugin for me

The comparison tab is empty. The console prints : 
`AttributeError: 'Window' object has no attribute 'set_menu_visible'`

**Comment by mastef** [comment]
Might be related to osx not having this feature, see : 
https://github.com/aziz/DistractionFreeWindow/issues/19
https://github.com/aziz/DistractionFreeWindow/commit/0570591b97ff8b111ae14af632a9629b211493ef

**Comment by DougTy** [comment]
@mastef What build of ST3 are you using?

I'm pretty sure `set_menu_visible` was added during beta at some point & not originally in the API, so if you're using an old version of ST, there won't be support for it. If you're for sure on the latest build, I unfortunately have no way of testing on OSX, but I can put in a check to skip this functionality & hope it works... However it is odd that no one else has reported this before.

(As a side note, it would be preferrable to create separate issues for new bugs in the future. Thanks for reporting this though! Hopefully we can get it all figured out.)

**Comment by mastef** [comment]
@DougTy It's okay if there's no support for it. The problem is just that the whole plugin simply doesn't work. Would be great with a check if this attribute exists ( and possibly the other attributes added in this PR ). I've created a new ticket here: #41

**Pull request merged**
